#!/bin/sh

ROOTDIR=`pwd`
INSTALLDIR="$ROOTDIR/install"

. $ROOTDIR/scripts/list-components

rm -rf $INSTALLDIR

for comp_path in $COMPONENTS; do
	cd $ROOTDIR
	if [ ! -d $comp_path ] ; then
		base_comp=`dirname $comp_path`
		if [ $base_comp == "." ] ; then
		    git clone git://git.freesmartphone.org/$comp_path.git
		else
			git clone git://git.freesmartphone.org/$base_comp.git
		fi
	else
		cd $ROOTDIR/$comp_path
		git pull
	fi
done

